name: Release

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: "FLOW 8 MIDI Controller"

    steps:
    - uses: actions/checkout@v2

    - name: Install cross-rs
      run: cargo install cross

    - name: Build Windows
      run: cross build --release --target x86_64-pc-windows-gnu

    - name: Archive .exe
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PROJECT_NAME }}-x86_64-pc-windows.exe
        path: target/release/*.exe

